# ***********************************************************
## Name: 王品力
## Class: 資管系三年級
## SID: S06490040
## Program Name: hw4_S06490040.ipynb
## Function: Numpy練習
## Homework: No.4
## Limitations: 照老師題目所要求
## Date: 2020/05/17
## ***********************************************************

In [1]:
import numpy as np #引入Numpy模組

## P1-1 以 NumPy 內建工具來產生 60 個介於 50 到 +99 之間的亂數整數，每一個整數大小為 64 位元。將這 60 個整數 任意 放入一個 6 X10 的陣列中，以每一列 (為單位， 分別 計算並輸出以下需求 數值需四捨五入制小數點後兩位數):
## a、 顯示 資料集的型態
## b、 平均數
## c、 中位數
## d、 標準差
## e、 變異數
## f、 集差值 ( 請參考如何使用 numpy.ptp() )，本題要的是特定一 列的集差值。
## 以上每一個子題限定使用numpy 提供的方法完成，每題超過一行指令就是錯的！

# =============================================================

In [2]:
P_1 = np.random.randint(-50, 100, size = (6, 10), dtype = "int64") #產生一個6*10的陣列，內容為64位元-50到99之間的亂數整數
print(P_1)                                                         #印出內容

[[ 56  73 -34  52  14  87   5  81  52  40]
 [ 23  52  52 -35  22  65  56  31  68 -19]
 [-14   2  61  48   1 -15 -27  38 -37  -5]
 [ 61  99 -31 -35 -23  74 -15  21 -25  81]
 [ 39  91 -30  44  23   5 -24  49   2  64]
 [ 13  66  32  51  67  64  49  64   2  57]]


### a、 顯示 資料集的型態

In [3]:
print(P_1[0].dtype,"\n",P_1[1].dtype,"\n",P_1[2].dtype,"\n",P_1[3].dtype,"\n",P_1[4].dtype,"\n",P_1[5].dtype) #印出P_1資料集每一列的資料型態
# 或是直接打P_1[0],P_1[1],P_1[2],P_1[3],P_1[4],P_1[5] 心純老師說上面或這個寫法都可以，都給分

int64 
 int64 
 int64 
 int64 
 int64 
 int64


### b、 平均數

In [4]:
print(np.around(np.mean(P_1, axis=1), decimals=2)) #印出P_1每列的平均數

[42.6 31.5  5.2 20.7 26.3 46.5]


### c、 中位數

In [5]:
print(np.around(np.median(P_1, axis=1), decimals=2)) #印出P_1每列的中位數

[52.  41.5 -2.   3.  31.  54. ]


### d、 標準差

In [6]:
print(np.around(np.std(P_1, axis=1), decimals=2)) #印出P_1每列的標準差

[35.82 33.21 31.22 50.28 36.54 22.05]


### e、 變異數

In [7]:
print(np.around(np.var(P_1, axis=1), decimals=2)) #印出P_1每列的變異數

[1283.24 1103.05  974.76 2528.01 1335.21  486.25]


### f、 集差值 ( 請參考如何使用 numpy.ptp() )，本題要的是特定一 列的集差值。

In [8]:
print(np.around(np.ptp(P_1, axis=1), decimals=2)) #印出P_1每列的極差值

[121 103  98 134 121  65]


                                ↑↑↑                   P1-1 Finish                    ↑↑↑

## P1-2 以 NumPy 內建工具來產生一個 3X4 的陣列 A ，以及一個 4X5 的陣列 B ，每
## 一個陣列的元素為介於 1 到 50 之間的亂數整數，每一個整數大小為 32 位
## 元。 請完成 以下 的 需求：
## a、 顯示陣列 A 和陣列 B
## b、 找出陣列 A 中每一列 ( row )的最大值。
## c、 找出陣列 A 第二 列 ( row ) 中所有小於 30 的數值 。
## d、 找出陣列 B 中每一行 或欄 ( column ) 的最大值。
## e、 找出陣列 B 第二行 (column) 中所有小於 30 的數值。
## f、 顯示 陣列 A 中第一 列 ( row ) 和陣列 B 中第一列的聯集結果 。
## g、 計算與輸出陣列 A 與陣列 B 相乘的結果 。
## h、 將兩個陣列扁平化後，輸出 陣列 A 交集 陣列 B 的集合運算結果。
## i、 同上一題 ，輸出陣列 A 差集 陣列 B 的 集合運算 結果。
## 以上每一個子題限定使用
## numpy 提供的方法完成，每題超過一行指令就是錯的！

# =============================================================

In [9]:
P_2A = np.random.randint(1, 51, size = (3, 4), dtype = "int32") #產生兩個3*4與4*5的陣列，內容為32位元1到50之間的亂數整數
P_2B = np.random.randint(1, 51, size = (4, 5), dtype = "int32")

### a、 顯示陣列 A 和陣列 B

In [10]:
print("array A:","\n",P_2A,"\n""\n","array B:","\n",P_2B) #顯示A和B陣列

array A: 
 [[44 27 16 10]
 [38 28 13  9]
 [36 36  6 11]] 

 array B: 
 [[10  1 16 38  8]
 [31 16 27 46  9]
 [47 35 17 40  4]
 [40  3 12 35 21]]


### b、 找出陣列 A 中每一列 ( row )的最大值。

In [11]:
print(np.max(P_2A, axis=1)) #印出陣列 A 中每一列 ( row )的最大值

[44 38 36]


### c、 找出陣列 A 第二 列 ( row ) 中所有小於 30 的數值 。

In [12]:
print(P_2A[1][P_2A[1]<30]) #印出陣列 A 第二 列 ( row ) 中所有小於 30 的數值

#print(np.where(P_2A[1]<30,P_2A[1],"N/A")) 用np.where也可，但缺點是不滿足條件的元素無法丟出array，需要用其他數字、字元字串來表示

[28 13  9]


### d、 找出陣列 B 中每一行 或欄 ( column ) 的最大值。

In [13]:
print(np.max(P_2B, axis=0)) #印出陣列 B 中每一行 或欄 ( column ) 的最大值

[47 35 27 46 21]


### e、 找出陣列 B 第二行 (column) 中所有小於 30 的數值。

In [14]:
print(P_2B[:,1][P_2B[:,1]<30]) #印出陣列 B 第二行 (column) 中所有小於 30 的數值

#print(np.where(P_2B[:,1]<30,P_2B[:,1],"N/A")) 用np.where也可，但缺點是不滿足條件的元素無法丟出array，需要用其他數字、字元字串來表示

[ 1 16  3]


### f、 顯示 陣列 A 中第一 列 ( row ) 和陣列 B 中第一列的聯集結果 。

In [15]:
print(np.union1d(P_2A[0], P_2B[0])) #印出陣列A中第一列和陣列B中第一列的聯集結果

[ 1  8 10 16 27 38 44]


### g、 計算與輸出陣列 A 與陣列 B 相乘的結果 。

In [16]:
print(np.dot(P_2A, P_2B)) #印出陣列A與陣列B內積後的結果

[[2429 1066 1825 3904  869]
 [2219  968 1693 3567  797]
 [2198  855 1782 3649  867]]


### h、 將兩個陣列扁平化後，輸出 陣列 A 交集 陣列 B 的集合運算結果。

In [17]:
print(np.intersect1d(np.ravel(P_2A), np.ravel(P_2B))) #先將陣列A,B扁平化後，印出它們的交集結果

[ 9 10 16 27 38]


### i、 同上一題 ，輸出陣列 A 差集 陣列 B 的 集合運算 結果。

In [18]:
print(np.setdiff1d(np.ravel(P_2A), np.ravel(P_2B))) #先將陣列A,B扁平化後，印出它們的差集結果

[ 6 11 13 28 36 44]


                              ↑↑↑                P1-2 Finish                 ↑↑↑

## P1-3 以 NumPy 內建工具來產生一個 5 X 5 的陣列 A ，以及一個 5 X5 的陣列 B ，其
## 中陣列 A 的元素為介於 1 到 50 之間由小到大的奇數，而陣列 B 的元素為介
## 於 1 到 50 之間由小到大的偶數，每一個整數 元素的 大小為 32 位元。請完成
## 以下的需求：
## a、 顯示陣列 A 和陣列 B
## b、 使用 np.concatenate() 方法，將陣列 A 與陣列 B 作垂直堆疊並顯示結果。
## c、 使用 np.concatenate() 方法， 將陣列 A 與陣列 B 作水平堆 疊 並顯示結果 。
## d、 陣列 A 和陣列 B 中的奇數列進行交換，並顯示交換後這兩個陣列的內容 。

# ===========================================================

In [19]:
P_3A = np.arange(1,50,2).reshape((5,5))  #宣告一個內容為1到50之間奇數的陣列
P_3B = np.arange(2,51,2).reshape((5,5))   ##宣告一個內容為1到50之間偶數的陣列

### a、 顯示陣列 A 和陣列 B

In [20]:
print("array A:","\n",P_3A,"\n""\n","array B:","\n",P_3B) #印出陣列A,B

array A: 
 [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 

 array B: 
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


### b、 使用 np.concatenate() 方法，將陣列 A 與陣列 B 作垂直堆疊並顯示結果。

In [21]:
print(np.concatenate((P_3A,P_3B), axis=0)) #利用np.concatenate()方法將陣列A,B，做垂直堆疊，並印出結果

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


 ### c、 使用 np.concatenate() 方法， 將陣列 A 與陣列 B 作水平堆 疊 並顯示結果 。

In [22]:
print(np.concatenate((P_3A,P_3B), axis=1)) #利用np.concatenate()方法將陣列A,B，做水平堆疊，並印出結果

[[ 1  3  5  7  9  2  4  6  8 10]
 [11 13 15 17 19 12 14 16 18 20]
 [21 23 25 27 29 22 24 26 28 30]
 [31 33 35 37 39 32 34 36 38 40]
 [41 43 45 47 49 42 44 46 48 50]]


### d、 陣列 A 和陣列 B 中的奇數列進行交換，並顯示交換後這兩個陣列的內容 。

In [23]:
P_3A[[0, 2, 4], :], P_3B[[0, 2, 4], :] = P_3B[[0, 2, 4], :], P_3A[[0, 2, 4], :]   #將P_3A與P_3B的奇數列對調
print("array A:","\n",P_3A,"\n""\n","array B:","\n",P_3B)               #印出兩個陣列的內容

array A: 
 [[ 2  4  6  8 10]
 [11 13 15 17 19]
 [22 24 26 28 30]
 [31 33 35 37 39]
 [42 44 46 48 50]] 

 array B: 
 [[ 1  3  5  7  9]
 [12 14 16 18 20]
 [21 23 25 27 29]
 [32 34 36 38 40]
 [41 43 45 47 49]]


                        ↑↑↑                       P1-3 Finish                         ↑↑↑