# 請輸入Student ID:s1116015 彭鍾碩

SVM

In [1]:
#import package
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn import ensemble, metrics
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
import math

In [2]:
# 開啟 CSV 檔案
dataset = pd.read_csv('train.csv',sep=',')
testset = pd.read_csv('test.csv',sep=',')

In [3]:
#將dataset shuffle
dataset = shuffle(dataset)
label = dataset.label
dataset = dataset[dataset.columns[:449]]

In [4]:
#svm
#引入library
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

#10-fold cross-validation 交叉驗證
kfold = KFold(10,True)
predicted = []
expected = []

#訓練模型
for train,test in kfold.split(dataset):
    X_train = dataset.iloc[train]
    Y_train = label.iloc[train]
    X_test = dataset.iloc[test]
    Y_test = label.iloc[test]
    svm = OneVsRestClassifier(SVC(gamma='scale')).fit(X_train,Y_train)
    expected.extend(Y_test)
    predicted.extend(svm.predict(X_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass shuffle=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [5]:
print("Macro-average: {0}".format(metrics.f1_score(expected,predicted,average='macro')))
print("Micro-average: {0}".format(metrics.f1_score(expected,predicted,average='micro')))
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

print("Average = macro")
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='macro'))

print("\n")
print("Average = micro")
print('precision:', metrics.precision_score(expected, predicted, average='micro')) 
print('recall:',metrics.recall_score(expected, predicted,average='micro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='micro'))

print("\n")
print("Average = weighted")
print('precision:', metrics.precision_score(expected, predicted, average='weighted'))
print('recall:',metrics.recall_score(expected, predicted,average='weighted'))
print('F1-score:',metrics.f1_score(expected,predicted,labels=[1,2,3,4],average='weighted'))

Macro-average: 0.971547756856576
Micro-average: 0.9724296381390006
              precision    recall  f1-score   support

           0       1.00      0.95      0.98       145
           1       0.95      0.90      0.93       207
           2       1.00      0.96      0.98       119
           3       0.90      0.97      0.93       238
           4       0.97      0.98      0.98       256
           5       1.00      1.00      1.00       264
           6       1.00      0.99      1.00       240
           7       0.98      0.99      0.99       272

    accuracy                           0.97      1741
   macro avg       0.98      0.97      0.97      1741
weighted avg       0.97      0.97      0.97      1741

[[138   1   0   0   6   0   0   0]
 [  0 187   0  20   0   0   0   0]
 [  0   0 114   5   0   0   0   0]
 [  0   8   0 230   0   0   0   0]
 [  0   0   0   0 252   0   0   4]
 [  0   0   0   0   0 264   0   0]
 [  0   0   0   1   0   0 238   1]
 [  0   1   0   0   1   0   0 270]]
A

In [37]:
testset = testset[testset.columns[:449]]

In [38]:
svm.predict(testset)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7], dtype=int64)

In [39]:
#從訓練資料隨機抓幾筆出來做測試
from numpy import random
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

#確認訓練資料的筆數
dataset= pd.read_csv('train.csv')
print('資料的形式:{}'.format(dataset.shape))

#numpy.random.randint(low, high=None, size=None, dtype='l')
#隨機選出10筆
random.seed(1)
index_random=random.randint(1,1740,10)
print(index_random)

資料的形式:(1741, 450)
[1062  236 1097  906  716 1670  848  961  145  130]


In [40]:
#從訓練資料取出這10筆資料
dataset_fortest = []
for i in index_random:
      dataset_fortest.append(dataset.iloc[i] [:449])
dataset_fortest = pd.DataFrame(dataset_fortest)
dataset_fortest

col1  col2  col3  col4  col5  col6  col7  col8   col9  col10  ...  \
1062  70.1  70.1  70.1  70.0  70.2  70.2  70.4  70.5   70.7   70.8  ...   
236   78.6  78.6  78.6  78.6  79.2  79.9  80.5  81.3   82.2   83.6  ...   
1097  81.4  81.4  81.4  81.5  81.8  82.0  82.3  82.6   82.9   83.1  ...   
906   76.2  76.2  76.2  76.2  76.4  76.7  77.0  77.5   78.2   79.2  ...   
716   69.7  69.7  69.8  69.8  72.0  71.3  72.4  75.7   75.4   77.2  ...   
1670  70.0  70.0  70.0  70.1  70.4  70.7  70.8  71.0   71.2   71.5  ...   
848   84.9  84.9  84.9  84.9  84.9  85.1  85.4  86.2   86.6   87.5  ...   
961   72.3  72.3  72.3  72.3  72.8  73.3  74.2  75.2   76.5   78.2  ...   
145   81.2  81.2  81.2  81.2  81.4  82.0  83.0  84.1   85.2   86.7  ...   
130   92.0  92.0  92.0  92.0  93.4  94.2  96.1  98.3  101.0  103.0  ...   

      col440  col441  col442  col443  col444  col445  col446  col447  col448  \
1062     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
236      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1097     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
906      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
716      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1670     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
848      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
961      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
145      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
130      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

      col449  
1062     0.0  
236      0.0  
1097     0.0  
906      0.0  
716      0.0  
1670     0.0  
848      0.0  
961      0.0  
145      0.0  
130      0.0  

[10 rows x 449 columns]

In [44]:
#預測
predicted = svm.predict(dataset_fortest)
predicted

array([5, 1, 5, 4, 4, 7, 4, 4, 3, 0], dtype=int64)

In [45]:
#實際
label1 = []
for i in index_random:
      label1.append(dataset.iloc[i] [-1])
label1 = pd.DataFrame(label1)
expected = label1.values
expected

array([[5.],
       [1.],
       [5.],
       [4.],
       [4.],
       [7.],
       [4.],
       [4.],
       [1.],
       [0.]])

In [47]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(label1,predicted,average='macro'))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         1
         1.0       1.00      0.50      0.67         2
         3.0       0.00      0.00      0.00         0
         4.0       1.00      1.00      1.00         4
         5.0       1.00      1.00      1.00         2
         7.0       1.00      1.00      1.00         1

    accuracy                           0.90        10
   macro avg       0.83      0.75      0.78        10
weighted avg       1.00      0.90      0.93        10

[[1 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 1]]
Accuracy: 90.00%
precision: 0.8333333333333334
recall: 0.75
F1-score: 0.7777777777777777


隨機森林

In [53]:
#Random Forest
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

#10-fold cross-validation
kfold = KFold(10,True)
predicted = []
expected = []

#訓練模型
for train, test in kfold.split(dataset):
    X_train = dataset.iloc[train]
    Y_train = label.iloc[train]
    X_test = dataset.iloc[test]
    Y_test = label.iloc[test]
    forest = ensemble.RandomForestClassifier(n_estimators = 100)
    forest.fit(X_train,Y_train)
    expected.extend(Y_test)
    predicted.extend(forest.predict(X_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass shuffle=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [54]:
print("Macro-average: {0}".format(metrics.f1_score(expected,predicted,average='macro')))
print("Micro-average: {0}".format(metrics.f1_score(expected,predicted,average='micro')))
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

print("Average = macro")
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='macro'))

print("\n")
print("Average = micro")
print('precision:', metrics.precision_score(expected, predicted, average='micro')) 
print('recall:',metrics.recall_score(expected, predicted,average='micro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='micro'))

print("\n")
print("Average = weighted")
print('precision:', metrics.precision_score(expected, predicted, average='weighted'))
print('recall:',metrics.recall_score(expected, predicted,average='weighted'))
print('F1-score:',metrics.f1_score(expected,predicted,labels=[1,2,3,4],average='weighted'))

Macro-average: 0.9960800797468271
Micro-average: 0.9959793222286043
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       145
           1       1.00      1.00      1.00       207
           2       1.00      1.00      1.00       119
           3       1.00      1.00      1.00       238
           4       1.00      0.99      0.99       256
           5       0.99      1.00      1.00       264
           6       1.00      1.00      1.00       240
           7       1.00      1.00      1.00       272

    accuracy                           1.00      1741
   macro avg       1.00      1.00      1.00      1741
weighted avg       1.00      1.00      1.00      1741

[[143   0   0   0   1   1   0   0]
 [  0 206   0   1   0   0   0   0]
 [  0   0 119   0   0   0   0   0]
 [  0   0   0 238   0   0   0   0]
 [  0   1   0   0 254   0   0   1]
 [  0   0   0   0   0 264   0   0]
 [  0   0   0   0   0   1 239   0]
 [  0   0   0   0   0   0   1 271]]


In [55]:
#從訓練資料隨機抓幾筆出來做測試
from numpy import random

#確認訓練資料的筆數
dataset= pd.read_csv('train.csv')
print('資料的形式:{}'.format(dataset.shape))

#numpy.random.randint(low, high=None, size=None, dtype='l')
#隨機選出10筆
random.seed(1)
index_random=random.randint(1,1740,10)
print(index_random)

資料的形式:(1741, 450)
[1062  236 1097  906  716 1670  848  961  145  130]


In [56]:
#從訓練資料取出這10筆資料
dataset_fortest = []
for i in index_random:
      dataset_fortest.append(dataset.iloc[i] [:449])
dataset_fortest = pd.DataFrame(dataset_fortest)
dataset_fortest

col1  col2  col3  col4  col5  col6  col7  col8   col9  col10  ...  \
1062  70.1  70.1  70.1  70.0  70.2  70.2  70.4  70.5   70.7   70.8  ...   
236   78.6  78.6  78.6  78.6  79.2  79.9  80.5  81.3   82.2   83.6  ...   
1097  81.4  81.4  81.4  81.5  81.8  82.0  82.3  82.6   82.9   83.1  ...   
906   76.2  76.2  76.2  76.2  76.4  76.7  77.0  77.5   78.2   79.2  ...   
716   69.7  69.7  69.8  69.8  72.0  71.3  72.4  75.7   75.4   77.2  ...   
1670  70.0  70.0  70.0  70.1  70.4  70.7  70.8  71.0   71.2   71.5  ...   
848   84.9  84.9  84.9  84.9  84.9  85.1  85.4  86.2   86.6   87.5  ...   
961   72.3  72.3  72.3  72.3  72.8  73.3  74.2  75.2   76.5   78.2  ...   
145   81.2  81.2  81.2  81.2  81.4  82.0  83.0  84.1   85.2   86.7  ...   
130   92.0  92.0  92.0  92.0  93.4  94.2  96.1  98.3  101.0  103.0  ...   

      col440  col441  col442  col443  col444  col445  col446  col447  col448  \
1062     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
236      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1097     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
906      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
716      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1670     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
848      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
961      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
145      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
130      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

      col449  
1062     0.0  
236      0.0  
1097     0.0  
906      0.0  
716      0.0  
1670     0.0  
848      0.0  
961      0.0  
145      0.0  
130      0.0  

[10 rows x 449 columns]

In [57]:
#預測
predicted = svm.predict(dataset_fortest)
predicted

array([5, 1, 5, 4, 4, 7, 4, 4, 3, 0], dtype=int64)

In [58]:
#實際的答案
label1 = []
for i in index_random:
      label1.append(dataset.iloc[i] [-1])
label1 = pd.DataFrame(label1)
expected = label1.values
expected

array([[5.],
       [1.],
       [5.],
       [4.],
       [4.],
       [7.],
       [4.],
       [4.],
       [1.],
       [0.]])

In [59]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(label1,predicted,average='macro'))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         1
         1.0       1.00      0.50      0.67         2
         3.0       0.00      0.00      0.00         0
         4.0       1.00      1.00      1.00         4
         5.0       1.00      1.00      1.00         2
         7.0       1.00      1.00      1.00         1

    accuracy                           0.90        10
   macro avg       0.83      0.75      0.78        10
weighted avg       1.00      0.90      0.93        10

[[1 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 1]]
Accuracy: 90.00%
precision: 0.8333333333333334
recall: 0.75
F1-score: 0.7777777777777777


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
