### Python資料科學套件
#### Python資料科學套件是用來處理、分析和視覺化我們取得的資料，主要是指 NumPy、Pandas 和 Matplotlib 三大套件，其簡單說明如下所示：
1. **<font color=#0000FF>NumPy套件</font>：一套強調<font color=#FF00FF>高效率陣列處理的Python數學套件</font>，可以幫助我們進行向量和矩陣運算。**
1. **<font color=#0000FF>Pandas套件</font>：<font color=#FF00FF>Python程式碼版的Excel試算表工具</font>，可以幫助我們進行資料處理和分析。**
1. **<font color=#0000FF>Matplotlib套件</font>：<font color=#FF00FF>2D/3D繪圖函數庫的資料視覺化工具</font>，支援各種統計圖表的繪製，可以幫助我們視覺化探索資料和顯示資料分析結果。**

#### **Python資料科學套件之間的關聯**<br></br>
<div><img src="pic/pythonecosystem.gif" width="700"/></div>
<br></br><br></br>

### **Python資料科學處理實務流程**<br></br>
<div><img src="pic/datascienceflowchart.gif" width="700"/></div>

## <ins>Numpy 教材與程式範例</ins>
#### NumPy [(wiki)](https://zh.wikipedia.org/wiki/NumPy)是能以高速進行陣列運算的函式庫。它是在 <font color=#0000FF>CPython</font> 上開發出來，可以克服傳統 CPython 上使用 list 或 tuple 藉由巢狀結構來表現一維與多維陣列的慢速存取缺點。
#### NumPy 陣列處理的特色：
1. **有效率（Efficient）**
2. **在記憶體內運算（In-memory, RAM）**
3. **佔連續記憶體位址（Contiguous or Strided)， 參考 [[1]](https://zhuanlan.zhihu.com/p/56684539), [[2]](https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/)**
4. **同質性的資料型態（Homogeneous but types can be algebraic）**

#### NumPy 中高速陣列運算的基礎便是多維陣列物件 <font color=#0000FF>ndarray</font>，除此之外 Numpy 也提供以下功能：
1. **Universal 函式（可回傳 ndarray 裡每個元素進行處理的結果）**
2. **各種函式群（數學函式/線性代數/統計處理）**
3. **與其他語言間的溝通介面（C/C++/Fortran）**
4. **能將陣列運算以 C 語言這樣的低階語言高速實作**
5. **能將資料統整於 CPU 的暫存器有效率讀出**
6. **能受惠於 CPU 的向量運算（Intel的 SSE 或 AVX 的 SIMD 運算）**

#### Numpy 生態系統（Ecosystem）
<img align="left" src="pic/numpyeco.gif" width="350" style="margin: 50px 20px" />
<img align="left" src="pic/numpy_scientific_domains.jpeg" width="500" style="margin: 0px 20px"/>
<br></br>
<img src="pic/ecosystem.png" width="400" style="margin: 0 auto"/>


**重要教學參考網頁：**
1. **[NumPy Manual（官網）](https://www.numpy.org/devdocs/index.html)**
1. **[NumPy Reference（官網）](https://docs.scipy.org/doc/numpy-1.16.1/reference/index.html)**
1. **[Scientific Computing Tools for Python](https://www.scipy.org/about.html#)**
1. **[SciPy+NumPy Lecture Notes](https://scipy-lectures.org/)**
1. **[NumPy, SciPy & Matplotlib – a scientist’s best friends](https://www.physik.uzh.ch/~python/python_2015-01/lecture4/che_numpy.pdf)**
1. **[Comparing SciPy, NumPy and Matplotlib](https://www.c-sharpcorner.com/article/comparing-scipy-numpy-matplotlib-and-pylab/)**
1. **[After 15 Long Years, a NumPy Paper Finally Appears!](https://syncedreview.com/2020/09/17/after-15-long-years-a-numpy-paper-finally-appears/)**
1. **[Why Python is the best choice for financial data modelling](https://medium.com/pyfinance/why-python-is-best-choice-for-financial-data-modeling-in-2019-c0d0d1858c45)**
1. **Numpy 的 statsmodels 套件 [（官網）](https://www.statsmodels.org/stable/index.html) [（所有的 API）](https://www.statsmodels.org/stable/api.html)**

In [2]:
import numpy as np

### 線性代數的數值運算函式庫
1. **[BLAS與LAPACK函式庫](https://chenhh.gitbooks.io/parallel_processing/blas/)**
2. **[「首席架構師推薦」數值計算庫一覽表](https://kknews.cc/zh-tw/code/bz4zrj6.html)**
3. **[矩陣運算庫 blas, cblas, openblas, atlas, lapack, mkl 之間有什麼關係](https://www.zhihu.com/question/27872849)**
4. **Intel MKL  [[1]](https://en.wikipedia.org/wiki/Math_Kernel_Library) [[2]](https://medium.com/@black_swan/ubuntu-%E4%BD%BF%E7%94%A8-intel-mkl-%E5%8A%A0%E9%80%9F-numpy-71ef7587af47) [[3]](https://scc.ustc.edu.cn/zlsc/sugon/intel/mkl/mkl_userguide/GUID-43679587-9B39-42A7-B516-5C437303126E.htm)**

In [ ]:
np.__config__.show()

1. **How to install BLAS in Anaconda? [[1]](https://anaconda.org/conda-forge/blas)**
2. **How to install OpenBlas in Anaconda? [[1]](https://anaconda.org/conda-forge/openblas)**
3. **How to install Intel MKL in Anaconda? [[1]](https://anaconda.org/intel/mkl)**
4. **How to install Lapack in Anaconda? [[1]](https://anaconda.org/conda-forge/lapack)**

In [ ]:
dir(np) 

#### 或輸入 < np. > 後按 <Tab 鍵>

In [ ]:
np.abs?

### **Numpy 資料型別**
<div><img src="pic/numpy_data_type.gif" width="500"/></div>

#### 詳細資料型別請參考 [(1)](https://docs.scipy.org/doc/numpy-1.16.1/reference/arrays.scalars.html)

### **使用資料型別的範例**

In [3]:
a = np.uint16(34) # 16位元無號整數
a

34

In [ ]:
dir(a)

In [ ]:
b = np.complex128([3.2, 4.2 + 1.09j]) #128位元複數的串列 
b

In [ ]:
c = np.array([2334.432, 2.23], dtype = np.single)  #單精準浮點數的 ndarray

In [ ]:
c1 = np.array([2334.432, 2.23])  #單精準浮點數的 ndarray

In [ ]:
c1

ndarray.flags 返回 ndarray 對象的內存信息，包含以下屬性：

|屬性|描述|
|:-|:-| 
| C_CONTIGUOUS | 數據是在一個單一的C風格的連續段中 |
| F_CONTIGUOUS | 數據是在一個單一的Fortran風格的連續段中 |
| OWNDATA | 數組擁有它所使用的內存或從另一個對像中借用它 |
| WRITEABLE | 數據區域可以被寫入，將該值設置為False，則數據為只讀 |
| ALIGNED | 數據和所有元素都適當地對齊到硬件上 |
| UPDATEIFCOPY | 這個數組是其它數組的一個副本，當這個數組被釋放時，原數組的內容將被更新 |

#### **提示：**
1. **Numpy的純量(Scalar)與Python的純量不完全相同，是稱為<font color=#0000FF>「陣列純量(array scalar)」</font>，意指既是純量也具有陣列的性質，NumPy想將純量與陣列用統一的機制來處理。**
2. **NumPy的純量為<font color=#FF0000>immutable(無法更動)</font>，與Python裡的數值型別相同。**

In [ ]:
c.flags
# Numpy的純量(Scalar)需參考 ndarray 屬性之一的 flag，請注意 WRITEABLE 是 False，代表 immutable(不可更動)與 Python 的數值型別相同

#### 向量（Vector）：向量是方向和大小值，常常用來表示速度、加速度和動力等，向量是一序列數值，有多種表示方法，在NumPy是使用<font color=#FF00FF>一維陣列</font>來表示，如下圖所示：
<div><img src="pic/vector.gif" width="200"/></div>

**陣列（Arrays）類似Python的串列（Lists），不過<font color=#FF0000>陣列元素的資料型態必須是相同的</font>，不同於清單可以不同。
陣列是程式語言的一種基本資料結構，屬於循序性的資料結構。**

In [ ]:
d = np.array([1, 2, 3]) # 陣列

In [ ]:
d[0], d[1], d[2]

In [ ]:
d[1] = 4

In [ ]:
d

In [ ]:
d.flags

### **NumPy 資料型別的指定範例 - 以 Generic Type 來指定** [[1](https://iter01.com/416824.html)], [[2](https://wizardforcel.gitbooks.io/ts-numpy-tut/content/3.html)], [[3](https://www.runoob.com/numpy/numpy-dtype.html)]

In [4]:
# dtype 物件指定例子，能以 dtype 引數指定的物件
dt = np.dtype('float')

In [5]:
dt

dtype('float64')

In [ ]:
type(dt)

In [ ]:
dir(dt)

In [ ]:
dt.type

In [6]:
# 產生 ndarray 時指定 dtype (使用 dtype 物件)
x = np.array([1.1, 2.1, 3.1], dtype = dt)

In [7]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [ ]:
# 產生 ndarray 時指定 dtype (直接以字串指定)
y = np.array([1.1, 2.1, 3.1], dtype = 'float')

In [ ]:
y.flags

### **NumPy 資料型別的指定範例 - 以 Python 內建型別來指定**

In [ ]:
z = np.array([1.1+2.1j, 2.1-3.4j], dtype = 'cfloat') # 複數
z

In [ ]:
z.dtype

In [ ]:
type(z)

### **NumPy 資料型別的指定範例 - 以 NumPy 內建型別指定方法或使用它的型別名稱縮寫、字碼來指定**

In [8]:
# 指定 dtype 物件
dt1 = np.dtype(np.int8)
dt1 = np.dtype('i1')

In [9]:
# 指定 dtype 物件
dt2 = np.dtype(np.int16)
dt2 = np.dtype('i2')

In [10]:
# 指定 dtype 物件
dt3 = np.dtype(np.int32)
dt3 = np.dtype('i4')

In [11]:
# 指定 dtype 物件
dt4 = np.dtype(np.int64)
dt4 = np.dtype('i8')

In [12]:
# 產生 ndarray 時指定 dtype
w = np.array([1.1+2.1j, 2.1-3.4j], dtype = 'complex64') # 複數
w = np.array([1.1+2.1j, 2.1-3.4j], dtype = 'c8') # 複數
w

array([1.1+2.1j, 2.1-3.4j], dtype=complex64)

[Data type objects (dtype)](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html#arrays-dtypes-constructing)

[numpy 學習彙總10-dtype數據類型](https://www.twblogs.net/a/5bf5eb39bd9eee37a060d2b4)

In [13]:
ints = np.ones(10, dtype = np.uint16)

In [14]:
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [ ]:
floats = np.ones(10, dtype = np.float32)

In [ ]:
floats

In [ ]:
np.issubdtype(ints.dtype, np.integer)

In [ ]:
np.issubdtype(floats.dtype, np.floating)

In [ ]:
np.float64.mro() #查看父資料型態類別

#### **使用 array() 函數建立 NumPy 陣列**

In [15]:
listdata = [1, 2, 3, 4, 5]     # 一個 python list 型別資料

tupledata = (1, 2, 3, 4, 5)    # 一個 python tupple 型別資料

a = np.array(listdata)    # 強迫轉成 numpy ndarray

b = np.array(tupledata)   # 強迫轉成 numpy ndarray

print("type(a) : ", type(a), '\n')  

# 用陣列索引值讀取資料
print("a[0] : ", a[0], "\na[1] : ", a[1], "\na[2] : ", a[2], "\na[3] : ", a[3], "\na[4] : ", a[4])

print()

print("type(b) : ", type(b), '\n')

#
# 原來的 tuple 資料在 numpy array 中變成可讀寫的模式
#
print("b.flags : \n", b.flags, '\n', sep = '')  # WRITEABLE : True 

b[0] = 5    
print("b = ", b, '\n') 

b[4] = 0
print("b = ", b)   

type(a) :  <class 'numpy.ndarray'> 

a[0] :  1 
a[1] :  2 
a[2] :  3 
a[3] :  4 
a[4] :  5

type(b) :  <class 'numpy.ndarray'> 

b.flags : 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


b =  [5 2 3 4 5] 

b =  [5 2 3 4 0]


### **體驗 NumPy 的運算速度**

In [16]:
import time
import numpy as np

def calculate(n):
    
    a = np.random.randn(n)    # 依照常態分佈產生亂數 
    
    b = list(a)    # 強迫轉型為 Python List 型別
    
    start_time = time.time()
    
    for _ in range(1000):
        
        sum_1 = np.sum(a)  # 使用 numpy 中的 sum()
        
    print('Using Numpy : %f sec.\n' % (time.time() - start_time))
    
    start_time = time.time()
    
    for _ in range(1000):
        
        sum_2 = sum(b)  # 使用 python 中內建的 sum()
        
    print('Without Using Numpy : %f sec.\n' % (time.time() - start_time))
    
    
n = int(input('輸入要產生用來測試的隨機亂數個數 : '))  # 建議以 10, 100, 1000, 10000, 100000 分別來測
print()
calculate(n)

輸入要產生用來測試的隨機亂數個數 : 10

Using Numpy : 0.005986 sec.

Without Using Numpy : 0.001995 sec.



#### 矩陣（Matrix）：矩陣類似向量，只是形狀是二維表格的列（Rows）和欄（Columns），我們需要使用列和欄來取得指定元素值，在NumPy是使用二維陣列方式來表示，如下圖所示：
<p>

<div><img src="pic/matrix.gif" width="300"/></div>

**Numpy中的多維陣列是指「二維陣列」（two-dimensional arrays）以上維度的陣列（含二維），屬於一維陣列的擴充，如果將一維陣列想像成是一度空間的線；二維陣列是二度空間的平面，需要使用2個索引才能定位二維陣列的指定元素。
在日常生活中，二維陣列的應用非常廣泛，只要是平面的各式表格，都可以轉換成二維陣列，例如：月曆、功課表等。如果繼續擴充二維陣列，還可以建立三維、四維等更多維的陣列，如下圖所示：**<p>

<div><img src="pic/numpy_matrix.gif" width="350"/></div>

**Numpy中不同維度的陣列圖像，如下圖所示：**<p>
<div><img src="pic/numpy-123d-array.png" width="700"/></div>

**請詳讀了解：[Converting 2D numpy array to 3D array without looping](https://stackoverflow.com/questions/47167305/converting-2d-numpy-array-to-3d-array-without-looping)**


#### **使用巢狀清單建立 NumPy 二維陣列**
<p>

<div><img src="pic/2Dmatrix1.gif" width="300"/></div>

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a[0, 0], a[0, 1], a[0, 2])

print(a[1, 0], a[1, 1], a[1, 2])

a[0, 0] = 6

a[1, 2] = 1

print("\na = \n", a)

1 2 3
4 5 6

a = 
 [[6 2 3]
 [4 5 1]]


In [ ]:
np.sum?

In [18]:
np.sum(a, axis = 0)   # 對每一個 column 內的資料做加總

array([10,  7,  4])

In [19]:
np.sum(a, axis = 1)   # 對每一個 row 內的資料做加總

array([11, 10])

#### **建立指定特定元素型態的陣列**

In [20]:
a = np.array([1, 2, 3, 4, 5], int) 

b = np.array((1, 2, 3, 4, 5), dtype = float) 

print("a = ", a, '\n') 

print("b = ", b, '\n')    

print("type(a) = ", type(a), ', ', 'a.dtype = ', a.dtype, '\n')

print("type(b) = ", type(b), ', ', 'b.dtype = ', b.dtype, '\n') 

a =  [1 2 3 4 5] 

b =  [1. 2. 3. 4. 5.] 

type(a) =  <class 'numpy.ndarray'> ,  a.dtype =  int32 

type(b) =  <class 'numpy.ndarray'> ,  b.dtype =  float64 



#### **陣列的建立函數，使用 arange()、zeros()、ones() 和 full()**

In [3]:
# NumPy 的 arange()函數類似 Python 的 range()函數，可以產生一序列數字的陣列

a = np.arange(5)
print("a = ", a, '\n')

b = np.arange(1, 6, 2)
print("b = ", b, '\n') 

c = np.zeros(2) 
print("c = ", c, '\n')  

d = np.zeros((2, 2)) 
print("d = \n", d, '\n')           

e = np.zeros((4, 3, 2)) 
print("e = \n", e, '\n')   

f = np.ones(2) 
print("f = ", f, '\n')   

g = np.ones((3, 2)) 
print("g = \n", g, '\n')         

h = np.ones((4, 3, 2)) 
print("h = \n", h, '\n')

i = np.full(2, 7)
print("i = ", i, '\n')  

j = np.full((2, 2), 7)
print("j = \n", j, '\n')

k = np.random.random((4, 3, 2))
np.set_printoptions(precision = 1)  # 設定列印至小數點後第一位就好
print("k = \n", k)

a =  [0 1 2 3 4] 

b =  [1 3 5] 

c =  [0. 0.] 

d = 
 [[0. 0.]
 [0. 0.]] 

e = 
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] 

f =  [1. 1.] 

g = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 

h = 
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]] 

i =  [7 7] 

j = 
 [[7 7]
 [7 7]] 

k = 
 [[[0.8 0.6]
  [0.5 1. ]
  [0.  0.9]]

 [[0.5 0.4]
  [0.7 0.4]
  [0.8 0.2]]

 [[0.5 0.4]
  [0.5 0.7]
  [0.2 0.6]]

 [[0.  0.2]
  [0.5 0.6]
  [0.9 0.7]]]


In [ ]:
c.dtype

In [ ]:
f.dtype

<div><img src="pic/numpy-3d-array-creation.png" width="700"/></div>

**多維陣列的結構、運算與圖型視覺話說明 [[1]](http://jalammar.github.io/visual-numpy/)**<br>
**如何印出陣列以及格式設定（np.set_printoptions） [[1]](https://www.brilliantcode.net/1045/numpy-tutorial-how-to-print-array/?cli_action=1605501304.327) [[2]](https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html)**

#### **陣列的建立函數，使用 zeros_like() 和 ones_like() 函數可以依據參數的範本陣列形狀，產生相同尺寸元素值都是 0 或 1 的陣列**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a =\n", a, '\n')

b = np.zeros_like(a)
print("b = \n", b, '\n')

c = np.ones_like(a)
print("c = \n", c, '\n')

d = np.eye(3)  # 單位矩陣
print("d = \n", d)

numpy.eye
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

生成一個對角線為 1，其餘位置為 0 的二維陣列。

引數：
1. N：int值，行數。
1. M：int值，列數，如果沒有則預設為N。
1. k：int型，可選項，對角線的下標，默認爲0表示的是主對角線，負數表示的是低對角，正數表示的是高對角。
1. dtype：返回的資料元素的格式，預設為float。
1. order：1.14.0版本後，可選引數 {'C', 'F'}

In [4]:
e0 = np.eye(4)
print("e0 = \n", e0, '\n')

e1 = np.eye(4, k = 1)
print("e1 = \n", e1, '\n')

e2 = np.eye(4, k = -1)
print("e2 = \n", e2, '\n')

e3 = np.eye(4, k = -3)
print("e3 = \n", e3, '\n')

e0 = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

e1 = 
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 

e2 = 
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] 

e3 = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]] 



In [5]:
f = np.random.rand(3)
print("f = ", f, '\n')

g = np.random.rand(3, 3)
print("g = \n", g)  

f =  [0.8 0.9 0.1] 

g = 
 [[0.4 0.3 0.6]
 [0.7 0.6 0.3]
 [0.2 1.  0.3]]


In [ ]:
np.eye?

In [ ]:
np.random?

#### **陣列維度的轉換**
**NumPy 可以使用 reshape() 函數，將一維陣列轉換成二維陣列，如下所示：**
<div><img src="pic/numpy-arrays-reshape.png" width="500"/></div>

In [ ]:
a = np.arange(16)
print("a = ", a, '\n')

b = a.reshape((4, 4))       # 將 a 由一維轉成二維
print("b = \n", b, '\n')

print("a = \n", a, '\n')    # a 本身陣列內容未改變 

c = np.arange(24).reshape(4, 3, 2)
print("c = \n", c, '\n')

d = np.array(range(10), float)
print("d = ", d, '\n')

e = d.reshape((5, 2))
print("e = \n", e)

In [ ]:
a.flags

In [ ]:
b.flags

#### **顯示 NumPy 陣列的屬性**
**NumPy 陣列是一個物件，提供相關屬性顯示陣列資訊。相關屬性的說明如下表所示：**<p>
<div><img src="pic/numpy_dtype.png" width="500"/></div>

In [8]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]]) # dtype = np.int32
 
print("type : ", type(a))
print("data type : ", a.dtype)
print("size : ", a.size)
print("shape : ", a.shape)
print("itemsize : ", a.itemsize)
print("ndim : ", a.ndim)
print("bytes : ", a.nbytes)  

type :  <class 'numpy.ndarray'>
data type :  int32
size :  25
shape :  (5, 5)
itemsize :  4
ndim :  2
bytes :  100


In [ ]:
a.T

##### 輸入<ndarray的變數名稱>. 並按下 <Tab鍵>，便會顯示屬性以及方法的一覽

In [ ]:
a.T

#### **走訪一維與二維陣列的元素**

In [ ]:
a = np.array([1, 2, 3, 4, 5])

for ele in a:
    print(ele)
    
print()
    
b = np.array([[1, 2], [3, 4], [5, 6]])

for ele in b:
    print(ele)

print()

for ele in b:
    for item in ele:
        print(str(item) + " ", end = "")


### **資料與記憶體的關係**
**NumPy 藉由將相同型別的資料配置於記憶體的整塊區域裡，使得高速處理得以實現。關於資料配置的方式，有與 C 語言相同的 <font color=#0000FF>列優先(row-major order)</font> 的配置方式，以及與 Fortran 語言相同的 <font color=#0000FF>行優先(column-major order)</font> 的配置方式。**<p>
<img  align="left" src="pic/rowcolumn_major.gif" width="200" alt="" style="margin: 20px 20px"/>
<img  align="left" src="pic/rowcolumn_major2.png" width="450" alt="" style="margin: 0px 20px"/>

### **列優先(row major)與行優先(column major)的配置方式**

In [ ]:
import numpy as np

a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]], dtype = 'i4', order = 'F')
b = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]], dtype = 'i4', order = 'C')

print('a.flags.f_contiguous = %r, a.flags.c_contiguous = %r' % (a.flags.f_contiguous, a.flags.c_contiguous) )

print(np.ravel(a, order = 'F'))
print(np.ravel(a, order = 'A'))   # When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering

print()

print(np.ravel(a, order = 'C'))
print(np.ravel(a, order = 'A'))   # When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering

print('\n')

print('b.flags.f_contiguous = %r, b.flags.c_contiguous = %r' % (b.flags.f_contiguous, b.flags.c_contiguous) )

print(np.ravel(b, order = 'C'))
print(np.ravel(b, order = 'A'))   # When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering

print()

print(np.ravel(b, order = 'F'))
print(np.ravel(b, order = 'A'))   # When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering

In [ ]:
a

In [ ]:
b

### Numpy 中的 ravel() 和 flatten() 函式用法：
1. **flatten() 與 ravel() 兩者均是將多維度的陣列物件轉為一維的陣列物件方法。**
1. **flatten() 處理後傳回的是一個陣列的 copy，簡言之運算之後的陣列不是與原陣列參照到相同的記憶體物件，而且會建立一個不同於原陣列物件的新物件，因此 flatten() 的運算速度相對較慢。**
1. **ravel() 處理後傳回的是一個陣列的 view，簡言之運算之後的陣列是與原陣列參照到相同的記憶體物件與記憶體位址，並沒有另外建立一個新的陣列物件，因此 ravel() 的運算速度相對較快。**
#### 二者比較：[[1]](https://www.geeksforgeeks.org/differences-flatten-ravel-numpy/), [[2]](http://www.tshopping.com.tw/thread-263170-1-1.html), [[3]](https://www.twcode01.com/numpy/numpy-array-manipulation.html), [[4]](http://violin-tao.blogspot.com/2017/06/numpy-2.html)
* **ravel()：[[1官網]](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html), [[2]](https://kknews.cc/zh-tw/code/4l3erz2.html)**
* **flatten()：[[1官網]](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html), [[2]](https://www.twblogs.net/a/5bdf35162b717720b51c3736)**
* **[Reshape Numpy Arrays in Python — A Step-By-Step Pictorial Tutorial](https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b)**

In [ ]:
# Python code to differentiate
# between flatten and ravel in numpy
import numpy as np

# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:")
print(a)

# To check the dimension of array (dimension =2)
# ( and type is numpy.ndarray )
print ("Dimension of array-> " , (a.ndim))

print("\nOutput for RAVEL")
# Convert nd array to 1D array
b = a.ravel()

# Ravel only passes a view of
# original array to array 'b'
print('After raval() :', b)

# Just to check the dimension i.e. 1
# (and type is same numpy.ndarray )
print ("Dimension of array->" ,(b.ndim))

# Modify a value 
b[0] = 1000
print('\nAfter modification :', b)

# Note here that value of original
# array 'a' at also a[0][0] becomes 1000
print("\nOriginal array after ravel() and modification :\n", a)

In [ ]:
import numpy as np

# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:")
print(a)

# To check the dimension of array (dimension =2)
# ( and type is numpy.ndarray )
print ("Dimension of array-> " , (a.ndim))

print("\nOutput for FLATTEN")
# Convert nd array to 1D array
b = a.flatten()

# Ravel only passes a view of
# original array to array 'b'
print('After flatten() :', b)

# Just to check the dimension i.e. 1
# (and type is same numpy.ndarray )
print ("Dimension of array->" ,(b.ndim))

# Modify a value 
b[0] = 1000
print('\nAfter modification :', b)

# Note here that value of original
# array 'a' at also a[0][0] becomes 1000
print("\nOriginal array after flatten() and modification :\n", a)

#### **載入與儲存檔案的陣列 - 將陣列儲存成檔案**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("a = ")
print(a, '\n')
print("a 形狀: " + str(a.shape), '\n')

b = np.array([1, 0, 1])
print("b = " + str(b), '\n')
print("b 形狀: " + str(b.shape), '\n')

c = a + b
print("c = \n", c)

In [ ]:
a = np.arange(10)

outputfile = "Example.npy"  # 輸出至檔案 Example.npy

with open(outputfile, 'wb') as fp:

    np.save(fp, a)


#### **載入與儲存檔案的陣列 - 將陣列儲存成檔案**

In [ ]:
a = np.array([[1,2,3], [4,5,6]])

outputfile = "Example.out" # 輸出至 text 或 csv 檔案 

np.savetxt(outputfile, a, delimiter=',') # 使用 savetxt() 將資料寫入 csv 檔

[Dump a NumPy array into a csv file](https://stackoverflow.com/questions/6081008/dump-a-numpy-array-into-a-csv-file)

#### **載入與儲存檔案的陣列 - 從檔案載入 NumPy 陣列**

In [ ]:
outputfile = "Example.npy"

with open(outputfile, 'rb') as fp:

    a = np.load(fp)

print(a)

#### **載入與儲存檔案的陣列 - 從 CSV 檔案載入 NumPy 陣列**

In [ ]:
outputfile = "Example.out"

a = np.loadtxt(outputfile, delimiter=',')

print(a)

#### **向量運算 – 向量與純量的四則運算**
**向量與純量（Scalar）可以進行加、減、乘和除的四則運算，純量是一個數值。以加法為例，例如：向量a有a1, a2, a3個元素，純量是s，如下圖所示：**
<p><div><img src="pic/addition.gif" width="400"/></div>

In [ ]:
a = np.array([1, 2, 3]) 
print("a = " + str(a))

s = 5 
print("s = " + str(s))

b = a + s       
print("a + s = " + str(b))    

b = a - s       
print("a - s = " + str(b))   

b = a * s       
print("a * s = " + str(b))  

b = a / s       
print("a / s = " + str(b))  

#### **向量運算 – 向量與純量的四則運算**

In [ ]:
a = np.array([1, 2, 3]) 
print("a = " + str(a))

s = 5 
print("s = " + str(s))

b = np.add(a, s)  # 使用 add()     
print("np.add(a, s) = " + str(b))    

b = np.subtract(a, s)   # 使用 subtract()  
print("np.subtract(a, s) = " + str(b))   

b = np.multiply(a, s)   # 使用 multiply()   
print("np.multiply(a, s) = " + str(b))  

b = np.divide(a, s)     # 使用 divide()  
print("np.divide(a, s) = " + str(b))  

#### **向量運算 – 向量與向量的四則運算**
**對於長度相同的2個向量，對應的向量元素也可以執行加、減、乘和除的四則運算來產生相同長度的向量。以加法為例，例如：向量 a 有 a1, a2, a3 個元素，s 有 s1, s2, s3，如下圖所示：**
<p>
<div><img src="pic/vectors.gif" width="450"/></div>

In [ ]:
a = np.array([1, 2, 3]) # a 與 s 向量長度相同
print("a = " + str(a))

s = np.array([4, 5, 6])  
print("s = " + str(s))

b = a + s       
print("a + s = " + str(b))    

b = a - s       
print("a - s = " + str(b))   

b = a * s       
print("a * s = " + str(b))  

b = a / s       
print("a / s = " + str(b)) 

#### **向量運算 – 向量與向量的四則運算**

In [ ]:
a = np.array([1, 2, 3]) 
print("a = " + str(a))

s = np.array([4, 5, 6])
print("s = " + str(s))

b = np.add(a, s)  # 使用 add()     
print("np.add(a,s) = " + str(b))    

b = np.subtract(a, s)   # 使用 subtract()  
print("np.subtract(a,s) = " + str(b))   

b = np.multiply(a, s)   # 使用 multiply()   
print("np.multiply(a,s) = " + str(b))  

b = np.divide(a, s)     # 使用 divide()  
print("np.divide(a,s) = " + str(b))  

#### **向量運算 – 向量的點積運算**
<p>
<div><img src="pic/dot_1d.png" width="300"/></div>

In [ ]:
a = np.array([1, 2, 3]) 
print("a = " + str(a))

s = np.array([4, 5, 6])  
print("s = " + str(s))

b = a.dot(s)       
print("a.dot(s) = " + str(b))    

#### **向量的內積（inner product）與外積（cross product）的計算**

In [ ]:
a, b = np.array([2, -4, 1]), np.array([3, 1, -2])

# inner product
print('inner product is : ', np.inner(a, b))

# cross product
print('cross product is : ', np.cross(a, b))

#### **矩陣的反矩陣（inverse）、行列式（determinant）與秩（rank）的計算**

In [ ]:
a = np.array([[1, 3], [-2, 1]])
print('a = ')
print(a)

# inverse matrix
print('The inverse matrix of a is : ')
print(np.linalg.inv(a))

# the determinant of matrix a
print('The det of a is : ', np.linalg.det(a))

# the rank of matrix a
print('The rank of a is : ', np.linalg.matrix_rank(a))

#### **切割一維陣列的元素**

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a = " + str(a))

b = a[1:3]     # 索引 1,2
print("a[1:3] = " + str(b))

b = a[:4]      # 索引 0,1,2,3
print("a[:4] = " + str(b))

b = a[3:]      # 索引 3,4,5,6,7,8
print("a[3:] = " + str(b))

b = a[2:9:3]   # 索引 2,5,8
print("a[2:9:3] = " + str(b))

b = a[::2]     # 索引 0,2,4,6,8
print("a[::2] = " + str(b))

b = a[::-1]    # 索引 8,7,6,5,4,3,2,1,0
print("a[::-1] = " + str(b))

b = a[2:-2]    # 索引 8,7,6,5,4,3,2,1,0
print("a[2:-2] = " + str(b))

#### **使用複雜索引取出元素 – 使用整數值索引**

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a = " + str(a))
print("a[0] = ", a[0], "\na[2] = ", a[2], "\na[-1] = ", a[-1] )  # 索引 0,2,最後1個 

b = a[[1, 3, 5, 7]]       # 索引 1,3,5,7
print("a[[1,3,5,7]] = " + str(b))

b = a[range(6)]           # 索引 0,1,2,3,4,5
print("a[range(6)] = " + str(b))

a[[2, 6]] = 10            # 同時更改多個索引值
print("a[[2,6]] = 10->" + str(a))

#### **使用複雜索引取出元素 – 使用布林值遮罩索引**

In [ ]:
a = np.array([14 ,8 ,10 ,11 ,6 ,3 ,18 ,13 ,12 ,9])
print("a = " + str(a))

mask = (a % 3 == 0)        # 建立布林值陣列

print("mask = " + str(mask))

b = a[mask]                # 使用布林值陣列取出值
print("a[mask] = " + str(b))

a[a % 3 == 0] = -1         # 同時更改多個True索引
print("a[a%3==0] = -1 ->" + str(a))

#### **矩陣運算 – 二維矩陣與純量的四則運算**
<p>
<div><img src="pic/matrix_scalar.gif" width="400"/></div>

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a = ", '\n', a)

s = 5 
print("s = " + str(s))

b = a + s       
print("a + s = ", '\n', b)

b = a - s       
print("a - s = ", '\n', b)

b = a * s       
print("a * s = ", '\n', b)

b = a / s       
print("a / s = ", '\n', b)

#### **矩陣運算 – 二維矩陣與純量的四則運算**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a = ", '\n', a)

s = 5 
print("s = " + str(s))

b = np.add(a, s)       
print("np.add(a,s) = ", '\n',  b)

b = np.subtract(a, s)       
print("np.subtract(a,s) = ", '\n', b)

b = np.multiply(a, s)       
print("np.multiply(a,s) = ", '\n', b)

b = np.divide(a, s)       
print("np.divide(a,s) = ", '\n', b)

#### **矩陣運算 – 矩陣與矩陣的四則運算**
<p>
<div><img src="pic/matrixs.gif" width="400"/></div>

In [ ]:
a = np.array([[1, 2], [3, 4]])
print("a = ", '\n', a)

s = np.array([[5, 6], [7, 8]])
print("s = ", '\n', s)

b = a + s       
print("a + s = ", '\n', b)

b = a - s       
print("a - s = ", '\n', b)

b = a * s       
print("a * s = ", '\n', b)

b = a / s       
print("a / s = ", '\n', b)

#### **矩陣運算 – 矩陣與矩陣的四則運算**

In [ ]:
a = np.array([[1, 2], [3, 4]])
print("a = ")
print(a)

s = np.array([[5, 6], [7, 8]])
print("s = \n", s)

b = np.add(a, s)       
print("np.add(a,s) = ", b)

b = np.subtract(a, s)       
print("np.subtract(a,s) = ", b)

b = np.multiply(a, s)       
print("np.multiply(a,s) = ", b)

b = np.divide(a, s)       
print("np.divide(a,s) = ", b)

#### **矩陣運算 – 矩陣與矩陣的點積運算**
<p>
<div><img src="pic/dot.gif" width="400"/></div>

In [ ]:
a = np.array([[1, 2], [3, 4]])
print("a = ", '\n',  a)

s = np.array([[5, 6], [7, 8]])
print("s = ", '\n', s)

b = a.dot(s)       
print("a.dot(s) = ", '\n', b)

#### **切割二維陣列的元素**
**NumPy二維陣列一樣可以使用切割運算子，從原始陣列切割出所需的子陣列，其語法如下所示：**<br>
<p style="text-align:center;"><b><font color=#FF0000>array[ start : end : step, start1 : end1 : step1 ]</font></b><br>
</p>
<br>
<img src="pic/slice.gif" width="250"/></div>

In [3]:
a = np.arange(11, 36)

a = a.reshape(5, 5)
print("a = ", '\n', a)

b = a[0, 1:4]     # 索引 [0,1~3]
print("a[0, 1:4] = ", b)

b = a[1:4, 0]     # 索引 [1~3,0]
print("a[1:4, 0] = ", b)

b = a[:2, 1:3]    # 索引 [0~1,1~2]
print("a[:2, 1:3] = ", '\n', b)

b = a[:, 1]        # 索引 [0~4,1]
print("a[:, 1] = ", b)

b = a[::2, ::2]   # 索引 [0~2~4,0~2~4]
print("a[::2, ::2] = ", '\n', b)

a =  
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
a[0, 1:4] =  [12 13 14]
a[1:4, 0] =  [16 21 26]
a[:2, 1:3] =  
 [[12 13]
 [17 18]]
a[:, 1] =  [12 17 22 27 32]
a[::2, ::2] =  
 [[11 13 15]
 [21 23 25]
 [31 33 35]]


<img src="pic/slice_sample.gif" width="400"/></div>

#### **使用複雜索引取出元素 – 使用整數值索引**

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("a = ", '\n', a, '\n')

b = a[[0, 1, 2], [0, 1, 0]]   # 索引 [0,0][1,1][2,0]
print("a[[0,1,2], [0,1,0]] = ", b, "\n")

b = np.array([a[0, 0], a[1, 1], a[2, 0]])  # 索引 [0,0][1,1][2,0]
print("np.array([a[0,0], a[1,1], a[2,0]]) = ", b, '\n')

idx = np.array([0, 2, 0, 1])
print("idx = " + str(idx), '\n')

b = a[np.arange(4), idx]     # 索引 [0,0][1,2][2,0][3,1]
print("a[np.arange(4), idx] = ", b, '\n')

a[np.arange(4), idx] += 10
print("a[np.arange(4), idx] += 10 -> ", '\n', a, '\n')

a =  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

a[[0,1,2], [0,1,0]] =  [1 5 7] 

np.array([a[0,0], a[1,1], a[2,0]]) =  [1 5 7] 

idx = [0 2 0 1] 

a[np.arange(4), idx] =  [ 1  6  7 11] 

a[np.arange(4), idx] += 10 ->  
 [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]] 



#### **使用複雜索引取出元素 – 使用布林值遮罩索引**

In [5]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a = ")
print(a)

mask = (a > 2)
print("\nmask = ")
print(mask)

b = a[mask]           # 使用布林值陣列取出值
print("\na[mask] = " + str(b))

a[a > 2] = -1         # 同時更改多個True索引
print("\na[a > 2] = -1 -> ")
print(a)

a = 
[[1 2]
 [3 4]
 [5 6]]

mask = 
[[False False]
 [ True  True]
 [ True  True]]

a[mask] = [3 4 5 6]

a[a > 2] = -1 -> 
[[ 1  2]
 [-1 -1]
 [-1 -1]]


#### **補充 np.indices() 的用法**

In [6]:
x = np.arange(20).reshape(5, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
row, col = np.indices((2, 3))

In [ ]:
row

In [ ]:
col

In [ ]:
x[row, col]

In [ ]:
x[row * 2, col]

#### **陣列廣播 – 使用廣播執行陣列相加運算**
**<font color=#FF0000>「廣播」（Broadcasting）</font>是NumPy機制，可以讓不同形狀的陣列執行數學運算，因為數學運算大都需要使用到二個陣列對應的元素；因此，NumPy會自動擴充二個陣列成為相同形狀，以便進行對應元素的數學運算。**
**例如：當一個小陣列和一個大陣列時，如果沒有廣播機制，我們需要自行先複製小陣列元素，將它擴充成與大陣列相同的形狀後，才能執行2個陣列的數學運算，NumPy廣播機制會自動幫我們擴充小陣列來執行運算，而不用自行撰寫Python程式碼來擴充陣列，如下圖所示：**<br></br><br></br>
<img src="pic/broadcast.gif" width="400"/></div>
<br></br><br></br>
**相關知識補充：[[1]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm), [[2]](https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/462108/), [[3 官網]](https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html), [[4]](https://openhome.cc/Gossip/DCHardWay/Broadcasting.html)**

In [ ]:
import numpy as np

a = np.array([0, 10, 20, 30]).reshape(4, 1)
print("a = ")
print(a, '\n')
print("a 形狀: " + str(a.shape), '\n')

b = np.array([0, 1, 2])
print("b = " + str(b), '\n')
print("b 形狀: " + str(b.shape), '\n')

c = a + b
print("c = \n", c)

<img src="pic/broadcast_sample.jpg" width="500"/></div>

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("a = ")
print(a, '\n')
print("a 形狀: " + str(a.shape), '\n')

b = np.array([1, 0, 1])
print("b = " + str(b), '\n')
print("b 形狀: " + str(b.shape), '\n')

c = a + b
print("c = \n", c)

#### **陣列形狀與內容操作 – 陣列平坦化**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a = ")
print(a, '\n')

b = a.ravel()
print("a.ravel() = " + str(b), '\n')

b = np.ravel(a)
print("np.ravel(a) = " + str(b))

#### **陣列形狀與內容操作 – 陣列平坦化**

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print("a = " + str(a), '\n')

b = np.reshape(a, (3, 2))
print("b = np.reshape(a,(3,2)) -> ")
print(b, '\n')

c = b.T
print("c = b.T -> ")
print(c, '\n')

c = b.transpose()
print("c = b.transpose() -> ")
print(c, '\n')

c = np.transpose(b)
print("c = np.transpose(b) -> ")
print(c, '\n')

#### **陣列形狀與內容操作 – 更改陣列的形狀**

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print("a = " + str(a), '\n')

b = np.reshape(a, (3, 2))
print("b = np.reshape(a, (3,2)) -> ")
print(b, '\n')

c = b.T
print("c = b.T -> ")
print(c, '\n')

c = b.transpose()
print("c = b.transpose() -> ")
print(c, '\n')

c = np.transpose(b)
print("c = np.transpose(b) -> ")
print(c)

#### **陣列形狀與內容操作 – 新增陣列的維度**

用於增加陣列 array 的維度 dimension
比如： 1D 會變成 2D，2D 會變成 3D……

x1 = np.array([1, 2, 3])
np.shape(x1)   # (3,)

x2 = x1[ : , np.newaxis]
np.shape(x2)   # (3, 1)

x3 = x1[np.newaxis, : ]
np.shape(x3)   # (1, 3)

In [ ]:
a = np.array([1, 2, 3])
print("a = " + str(a), '\n')

b = a[:, np.newaxis]
print("b = a[:, np.newaxis] -> ")
print(b)
print("b.shape : ", b.shape)

print()

b = a[np.newaxis, :]
print("b = a[np.newaxis, :] -> ")
print(b)
print("b.shape : ", b.shape)

#### **陣列形狀與內容操作 – 陣列複製、填滿值和連接陣列**

In [ ]:
a = np.array([1, 2, 3])
print("a = " + str(a))

b = a.copy()
print("\nb = a.copy() -> " + str(b))

b.fill(4)
print("\nb.fill(4) = " + str(b))

c = np.concatenate((a, b))
print("\nc = np.concatenate((a, b)) -> " + str(c))

#### **陣列形狀與內容操作 – 連接多個二維陣列**
**當使用np.concatenate()函數連接多個二維陣列時，我們可以指定參數axis軸的連接方向，參數值 0 是直向，可以連接在二維陣列的下方；參數值 1 是橫向，每一個陣列是連接在陣列的右方!**

In [ ]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])

c = np.concatenate((a, b))
print("c = np.concatenate((a, b)) -> ")
print(c)

c = np.concatenate((a, b), axis = 0)   # 直向連接
print("\nc = np.concatenate((a, b), axis = 0) -> ")
print(c)

c = np.concatenate((a, b), axis = 1)   # 橫向連接
print("\nc = np.concatenate((a, b), axis = 1) -> ")
print(c)

#### **亂數函數**
**NumPy的random子模組提供多種函數來產生亂數，和讓我們產生一整個陣列元素值的亂數值，相關函數的說明如下表所示：**<br>
<img src="pic/randseed.png" width="500"/></div>

In [6]:
np.random.seed(293423)

v1 = np.random.random()
v2 = np.random.random()
print('(v1, v2) = (%f, %f)' % (v1, v2) )

v3 = np.random.randint(5, 10)
v4 = np.random.randint(1, 101)
print('\n(v3, v4) = (%d, %d)' % (v3, v4) )

(v1, v2) = (0.336772, 0.526934)

(v3, v4) = (6, 46)


In [ ]:
np.random?

#### **使用亂數函數來產生陣列元素**

In [7]:
a = np.random.rand(5)
print("np.random.rand(5) = ")
print(a)

b = np.random.rand(3, 2)  
print("\nnp.random.rand(3,2) = ")
print(b)

c = np.random.randint(5, 10, size = 5)
print("\nnp.random.randint(5, 10, size = 5)")
print(c)

d = np.random.randint(5, 10, size = (2, 3))
print("\nnp.random.randint(5, 10, size = (2, 3))")
print(d)

np.random.rand(5) = 
[0.3 0.8 0.1 0.2 0.3]

np.random.rand(3,2) = 
[[0.1 0.4]
 [0.4 0.8]
 [0.5 0.5]]

np.random.randint(5, 10, size = 5)
[5 7 7 7 5]

np.random.randint(5, 10, size = (2, 3))
[[6 6 8]
 [6 6 5]]


#### **數學函數 – 三角函數**

In [ ]:
a = np.array([30, 45, 60]) 

print(np.sin(a * np.pi / 180), '\n')

print(np.cos(a * np.pi / 180), '\n') 

print(np.tan(a * np.pi / 180)) 

#### **數學函數 – 四捨五入函數**
**NumPy的around()函數是四捨五入函數，第2個參數指定四捨五入是哪一個十進位值的位數，預設值是0（沒有小數），1是小數點下一位；-1是10進位!**

In [9]:
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
print("a = " + str(a))

print('\nnp.around(a) = ', np.around(a))

print('\nnp.around(a, decimals = 1) = ', np.around(a, decimals = 1) ) # 1指小數點下一位

print('\nnp.around(a, decimals = -1) = ', np.around(a, decimals = -1)) # -1指10進位數

a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 
print("\na = " + str(a))

b = np.floor(a)
print("\nfloor() = " + str(b))

b = np.ceil(a)
print("\nceil() = " + str(b))

a = [  1.    5.5 123.    0.6  25.5]

np.around(a) =  [  1.   6. 123.   1.  26.]

np.around(a, decimals = 1) =  [  1.    5.6 123.    0.6  25.5]

np.around(a, decimals = -1) =  [  0.  10. 120.   0.  30.]

a = [-1.7  1.5 -0.2  0.6 10. ]

floor() = [-2.  1. -1.  0. 10.]

ceil() = [-1.  2. -0.  1. 10.]


### **陣列與矩陣的使用與比較**

In [ ]:
A = np.array([[1, 2], [3, 4]])   # 產生陣列 (ndarray)

B = np.matrix([[1, 2], [3, 4]])  # 產生矩陣 (matrix)

**使用矩陣產生的方式，可在許多複雜的計算時可以提高算式的可讀性！
例如要計算以下的算式：**
              $S=(ABA^T)^{-1}$

In [ ]:
# 使用 ndarray 的寫法
S = np.linalg.inv(A.dot(B.dot(A.T)))
print("S = \n", S, '\n')

# 使用 matrix 的寫法
S = np.linalg.inv( A * B * A.T )    # 可讀性高
print("S = \n", S, '\n')

# NumPy v1.0+ 與 Python 3.5+ 之後有增加 '@' 運算子給 ndarray 陣列使用，以提高可讀性！
S = np.linalg.inv( A @ B @ A.T)
print("S = \n", S, '\n')

### np.where() 的使用
**numpy.where(condition[, x, y])，基於條件condition，返回值來自 x(True) 或者 y(False)。 請參考 [[1]](https://www.delftstack.com/zh-tw/api/numpy/python-numpy-where/) [[2]](https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/358538/)**

In [ ]:
np.where?