## <font color=#0000FF>程式作業六</font>
1. **繳交期限為<font color=#FF6600> 2021/06/08 24:00</font> 以前上傳至 Moodle LMS 教學平台。**
2. **上傳作業時，必須完成以下幾件事：**
    * **將目前您所看到的此檔案(hw6.ipynb)，改為(<font color=#FF00FF>您的學號</font><font color=#0000FF>_hw6.ipynb</font>)。**
    * **建立一個全新的資料夾，將上述作業檔案置入，並將資料夾的名稱改為<font color=#FF00FF>您的學號</font>。**
    * **將上述包含作業的資料夾以 <font color=#FF0000>ZIP</font> 格式壓縮後上傳。**

3. **<font color=#FF0000>注意事項：所有程式作業應積極相互討論，但不得寫出同一版本或相互抄襲。您所完成繳交的作業是否有抄襲由評分的助教自行判斷，不會找您來確認，因為不會有兩個人會寫出相同的程式！所以強烈建議不要任意將自己已經完成的作業程式碼公開分享給其他同學。</font>**
4. **評分依據：**
    1. **標頭註解與指令註解完整度    <font color=#0000FF>30%</font>**
    2. **程式的輸出入格式與內容 <font color=#0000FF>20%</font>**
    3. **程式執行正確性(含)	   <font color=#0000FF>50%</font>**
5. **標頭註解與指令註解的撰寫請參考教學平台上老師提供的範例，至於要使用 Markdown 或 Code comments 的方式來撰寫請自選，程式盡量【逐行】或以【區塊方式】加註解說明，越完整清楚越好。**

### <font color=#FF6600>作業內容</font>

1. **本次作業限用 NumPy 指令語法。**
1. **作業必須在 Jupyter Notebook 上完成。**
1. **本次作業包含二個大題，請依序將每一個大題中的作業要求寫在指定的 cell 內。**

### <font color=#0000FF>第一題：</font>
***
**以 NumPy 內建工具來產生 60 個介於 -50 到 +99 之間的亂數整數，每一個整數大小為 64 位元。將這 60 個整數任意放入一個 6X10 的陣列中，以每一列(row)為單位，分別計算並輸出以下需求，其數值顯示於螢幕時需四捨五入制小數點後兩位數，遇缺補零(例：15.4 須表示成 15.40)，其詳細細節請參考 numpy 中的 set_printoptions()：**
1. **產生此矩陣並列印結果(請參考如何使用 numpy 中的 random())**
1. **顯示此矩陣每一列(row)資料集的型態(請參考如何使用 numpy 中的 apply_along_axis())**
1. **計算並顯示每一列(row)資料集的平均數(請參考如何使用 numpy 中的 mean(), around())**
1. **計算並顯示每一列(row)資料集的中位數(請參考如何使用 numpy 中的 median(), around())**
1. **計算並顯示每一列(row)資料集的標準差(請參考如何使用 numpy 中的 std(), around())**
1. **計算並顯示每一列(row)資料集的變異數(請參考如何使用 numpy 中的 var(), around())**
1. **計算並顯示每一列(row)資料集的集差值，即每列中最大值與最小值之間的差距(請參考如何使用 numpy 中的 ptp())**

#### <font color=#FF0000>※ 以上每一個子題限定使用 Numpy 提供的方法完成；切記：每題答案如果超過二行指令就是錯的！</font>

In [2]:
import numpy as np     # 讀入 Numpy 函式庫

### 設定以下各小題將結果列印於螢幕上時，必須列印至小數點後二位數，且小數部分遇缺補零

In [4]:
np.set_printoptions(precision=2, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None) 
#調整格式設定

### 1. 產生矩陣資料並列印其結果

In [5]:
ram = np.random.randint(-50, 100, size = (6, 10), dtype = "int64") #用ramdon中的randint來跑出-50~99的6*10矩陣
print(ram)                                                         #印出矩陣

[[ 82 -21 -41  89  78  59   8 -13  17 -27]
 [ 24  21   1  24  -2  82 -24 -22  65  75]
 [ 95  75  43 -22 -15  14  95  93   4 -13]
 [ 33  71 -29  26   1  66  83  69  40  26]
 [ 44  68  90 -33  86  58  31   3  99  19]
 [ 81  90  76 -17  64 -11  68  -3 -33 -35]]


### 2. 顯示此矩陣每一列資料集的型態

In [6]:
print("\r",ram[0].dtype,"\n",ram[1].dtype,"\n",ram[2].dtype,"\n",ram[3].dtype,"\n",ram[4].dtype,"\n",ram[5].dtype) #印出每列的資料型別

 int64 
 int64 
 int64 
 int64 
 int64 
 int64


### 3. 計算並顯示每一列(row)資料集的平均數

In [8]:
print(np.around(np.mean(ram, axis=1),decimals=2))#印出每列的平均數

[23.1 24.4 36.9 38.6 46.5 28. ]


### 4. 計算並顯示每一列(row)資料集的中位數

In [85]:
print(np.around(np.median(ram, axis=1), decimals=2))#印出每列的中位數

[11.  19.  37.   8.5 38.  27. ]


### 5. 計算並顯示每一列(row)資料集的標準差

In [86]:
print(np.around(np.std(ram, axis=1), decimals=2))#印出每列的標準差

[43.48 39.68 44.05 44.28 41.18 43.47]


### 6. 計算並顯示每一列(row)資料集的變異數

In [87]:
print(np.around(np.var(ram, axis=1), decimals=2)) #印出每列的變異數

[1890.29 1574.36 1940.56 1961.04 1695.69 1889.25]


### 7. 計算並顯示每一列(row)資料集的集差值

In [88]:
print(np.around(np.ptp(ram, axis=1), decimals=2)) #印出每列的極差值 

[118 115 143 138 130 133]


### <font color=#0000FF>第二題：</font>
***
**以 NumPy 內建工具來產生一個 3X4 的陣列 A，以及一個 4X5 的陣列 B，每一個陣列的元素為介於 1 到 50 之間的亂數整數，以及每一個整數大小限定為 32 位元。請完成以下的需求：**
1. **產生矩陣 A 與 B (請參考如何使用 numpy 中的 random())**
1. **分別列印矩陣 A 與 B 的資料內容**
1. **找出並顯示矩陣 A 中每一列(row)的最大值(請參考如何使用 numpy 中的 amax())**
1. **找出並顯示矩陣 A 中第二列(2nd row)中所有小於 30 的數值(請參考如何使用 numpy 中的 where())**
1. **找出並顯示矩陣 B 中每一行或欄(column)中的最大值(請參考如何使用 numpy 中的 amax())**
1. **找出並顯示矩陣 B 中第二行(2nd column)中所有小於 30 的數值(請參考如何使用 numpy 中的 where())**
1. **顯示矩陣 A 中第一列(1st row)和矩陣 B 中第一列(1st row)的聯集結果(請參考如何使用 numpy 中的 union1d())**
1. **計算與輸出矩陣 A 與矩陣 B 相乘的結果(請參考如何使用 numpy 中的 dot())**
1. **將兩個矩陣扁平化後，輸出矩陣 A 與矩陣 B 的交集運算結果(請參考如何使用 numpy 中的 intersect1d()、ravel())**

#### <font color=#FF0000>※ 以上每一個子題限定使用 Numpy 提供的方法完成；切記：每題答案如果超過二行指令就是錯的！</font>

In [ ]:
import numpy as np     # 讀入 Numpy 函式庫

### 1. 產生矩陣 A 與 B

In [89]:
A = np.random.randint(1, 51, size = (3, 4), dtype = "int32") #產生兩個3*4與4*5的陣列，內容為32位元1到50之間的亂數整數
B = np.random.randint(1, 51, size = (4, 5), dtype = "int32")

### 2. 分別列印矩陣 A 與 B 的資料內容

In [91]:
print("array A:","\n",A)       #列印A和B陣列
print("array B:","\n",B)

array A: 
 [[48 11 29 10]
 [39 38 22 27]
 [47 47  4 49]]
array B: 
 [[26 16 43 27 41]
 [ 1 32 48  8 19]
 [ 8 22 40 45 39]
 [16 38 26 44 36]]


### 3. 找出並顯示矩陣 A 中每一列(row)的最大值

In [92]:
print(np.max(A, axis=1)) #印出陣列 A 中每一列 ( row )的最大值

[48 39 49]


### 4. 找出並顯示矩陣 A 中第二列(2nd row)中所有小於 30 的數值

In [96]:
print(A[1][A[1]<30])   #印出陣列 A 第二 列 ( row ) 中所有小於 30 的數值

[22 27]


### 5. 找出並顯示矩陣 B 中每一行或欄(column)中的最大值

In [97]:
print(np.max(B, axis=0)) #印出陣列 B 中每一行 或欄 ( column ) 的最大值

[26 38 48 45 41]


### 6. 找出並顯示矩陣 B 中第二行(2nd column)中所有小於 30 的數值

In [98]:
print(B[:,1][B[:,1]<30]) #印出陣列 B 第二行 (column) 中所有小於 30 的數值


[16 22]


### 7. 顯示矩陣 A 中第一列(1st row)和矩陣 B 中第一列(1st row)的聯集結果

In [99]:
print(np.union1d(A[0], B[0])) #印出陣列A中第一列和陣列B中第一列的聯集結果

[10 11 16 26 27 29 41 43 48]


### 8. 計算與輸出矩陣 A 與矩陣 B 相乘的結果

In [100]:
print(np.dot(A, B))#印出陣列A與陣列B內積後的結果

[[1651 2138 4012 3129 3668]
 [1660 3350 5083 3535 4151]
 [2085 4206 5711 3981 4740]]


### 9. 將兩個矩陣扁平化後，輸出矩陣 A 與矩陣 B 的交集運算結果

In [101]:
print(np.intersect1d(np.ravel(A), np.ravel(B))) #先將陣列A,B扁平化後，印出它們的交集結果

[22 27 38 39 48]
